# Generated by Django 4.2.5 on 2023-10-24 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImagesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        default="djangodbmodelsfieldscharfield",
                        max_length=200,
                        verbose_name="Слаг",
                    ),
                ),
                ("url", models.URLField(max_length=2000, verbose_name="URL")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/%Y/%m/%d", verbose_name="Изображение"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["-created"], name="images_imag_created_5635e1_idx"
                    )
                ],
            },
        ),
    ]
