# Generated by Django 4.2.5 on 2023-10-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagesmodel",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, verbose_name="Слаг"),
        ),
    ]
