# Generated by Django 4.2.5 on 2023-10-24 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0002_alter_imagesmodel_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagesmodel",
            name="users_like",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Понравилось"
            ),
        ),
    ]
