# Generated by Django 4.2.5 on 2023-11-25 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0003_imagesmodel_users_like"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagesmodel",
            options={
                "ordering": ("-created",),
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
    ]
